#!/bin/bash
# This file is used by docker hub to build the image

docker build --build-arg VCS_REF=`git rev-parse HEAD` \
    --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
    -t $IMAGE_NAME .
