#!/bin/bash

# Use manifest-tool to create the manifest, given the experimental
# "docker manifest" command isn't available yet on Docker Hub.

docker manifest create $IMAGE_NAME $IMAGE_NAME-amd64 $IMAGE_NAME-arm32v7 $IMAGE_NAME-arm64v8

docker manifest annotate $IMAGE_NAME $IMAGE_NAME-amd64 --arch amd64 --os linux
docker manifest annotate $IMAGE_NAME $IMAGE_NAME-arm32v7 --arch arm --os linux --variant v7
docker manifest annotate $IMAGE_NAME $IMAGE_NAME-arm64v8 --arch arm64 --os linux --variant v8

docker manifest push $IMAGE_NAME